profile: local

server:
  port: 8081

info:
  name: ${spring.application.name}
  description: Tamer
  enviroment: ${spring.profiles.active}
  version: 0.0.1

logging:
  level:
    root: info
    org.springframework.data.r2dbc: DEBUG

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/tamer?useSSL=false&characterEncoding=utf8
    username: tamer
    password: tamer12@@