profile: local

server:
  port: 8081

info:
  name: ${spring.application.name}
  description: Tamer
  enviroment: ${spring.profiles.active}
  version: 0.0.1

logging:
  level:
    root: info
    org.springframework.data.r2dbc: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/tamer?useSSL=false&characterEncoding=utf8
    username: tamer
    password: tamer12@@

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 561204417726-27upjegsko14qohub5rr117pceemah1n.apps.googleusercontent.com
            client-secret: p6hFJ7TSNjqHBwEclqmF6q5w
            redirect-uri: "http://localhost:8081/login/oauth2/code/google"
            scope: profile,email,openid
          kakao:
            authorization-grant-type: authorization_code
            scope: profile, account_email
            redirect-uri: "http://localhost:8081/login/oauth2/code/kakao"
            client-name: Kakao
            client-authentication-method: POST
            client-id: 72fb19cb6258b29fc4e77521b4ad9433
            client-secret: 320gN6YS7c6bwb2dHtxvMqOcmOyhMFWE
            response_type: code
          naver:
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8081/login/oauth2/code/naver"
            client-name: Naver
            client-authentication-method: POST
            client-id: xxxxxxxxxxxxxxxxxxxxxxxx
            client-secret: xxxxxxxxxxxxxxxxxxxxxxxx
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response